package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * EmailVer generated by hbm2java
 */
public class EmailVer implements java.io.Serializable {

	private Integer emailVerid;
	private String email;
	private String code;
	private Date lastTime;

	public EmailVer() {
	}

	public EmailVer(String email, String code, Date lastTime) {
		this.email = email;
		this.code = code;
		this.lastTime = lastTime;
	}

	public Integer getEmailVerid() {
		return this.emailVerid;
	}

	public void setEmailVerid(Integer emailVerid) {
		this.emailVerid = emailVerid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

}
