package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

/**
 * Filter generated by hbm2java
 */
public class Filter implements java.io.Serializable {

	private Integer filterid;
	private Integer filterTypeid;
	private String filterName;
	private String describe;
	private Boolean isDeleted;

	public Filter() {
	}

	public Filter(Integer filterTypeid, String filterName, String describe, Boolean isDeleted) {
		this.filterTypeid = filterTypeid;
		this.filterName = filterName;
		this.describe = describe;
		this.isDeleted = isDeleted;
	}

	public Integer getFilterid() {
		return this.filterid;
	}

	public void setFilterid(Integer filterid) {
		this.filterid = filterid;
	}

	public Integer getFilterTypeid() {
		return this.filterTypeid;
	}

	public void setFilterTypeid(Integer filterTypeid) {
		this.filterTypeid = filterTypeid;
	}

	public String getFilterName() {
		return this.filterName;
	}

	public void setFilterName(String filterName) {
		this.filterName = filterName;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
