package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Ingredient generated by hbm2java
 */
public class Ingredient implements java.io.Serializable {

	private Integer ingredientid;
	private String ingredientName;
	private String unit;
	private Date updateTime;

	public Ingredient() {
	}

	public Ingredient(String ingredientName, String unit, Date updateTime) {
		this.ingredientName = ingredientName;
		this.unit = unit;
		this.updateTime = updateTime;
	}

	public Integer getIngredientid() {
		return this.ingredientid;
	}

	public void setIngredientid(Integer ingredientid) {
		this.ingredientid = ingredientid;
	}

	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
