package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Recipe generated by hbm2java
 */
public class Recipe implements java.io.Serializable {

	private Integer recipeid;
	private String mainPic;
	private String title;
	private String describe;
	private String difficulty;
	private String prepareTime;
	private String cookTime;
	private Integer uid;
	private String serves;
	private String hardwood;
	private String cookDurationDesc;
	private Date updateTime;
	private int  ingredientSize;

	public int getIngredientSize() {
		return ingredientSize;
	}

	public void setIngredientSize(int ingredientSize) {
		this.ingredientSize = ingredientSize;
	}

	public Recipe() {
	}

	public Recipe(String mainPic, String title, String describe, String difficulty, String prepareTime, String cookTime,
			Integer uid, String serves, String hardwood, String cookDurationDesc, Date updateTime,int ingredientSize) {
		this.mainPic = mainPic;
		this.title = title;
		this.describe = describe;
		this.difficulty = difficulty;
		this.prepareTime = prepareTime;
		this.cookTime = cookTime;
		this.uid = uid;
		this.serves = serves;
		this.hardwood = hardwood;
		this.cookDurationDesc = cookDurationDesc;
		this.updateTime = updateTime;
		this.ingredientSize = ingredientSize;
	}

	public Integer getRecipeid() {
		return this.recipeid;
	}

	public void setRecipeid(Integer recipeid) {
		this.recipeid = recipeid;
	}

	public String getMainPic() {
		return this.mainPic;
	}

	public void setMainPic(String mainPic) {
		this.mainPic = mainPic;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public String getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(String difficulty) {
		this.difficulty = difficulty;
	}

	public String getPrepareTime() {
		return this.prepareTime;
	}

	public void setPrepareTime(String prepareTime) {
		this.prepareTime = prepareTime;
	}

	public String getCookTime() {
		return this.cookTime;
	}

	public void setCookTime(String cookTime) {
		this.cookTime = cookTime;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getServes() {
		return this.serves;
	}

	public void setServes(String serves) {
		this.serves = serves;
	}

	public String getHardwood() {
		return this.hardwood;
	}

	public void setHardwood(String hardwood) {
		this.hardwood = hardwood;
	}

	public String getCookDurationDesc() {
		return this.cookDurationDesc;
	}

	public void setCookDurationDesc(String cookDurationDesc) {
		this.cookDurationDesc = cookDurationDesc;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
