package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

/**
 * RecipeFilter generated by hbm2java
 */
public class RecipeFilter implements java.io.Serializable {

	private Integer recipeFilterid;
	private Integer recipeid;
	private Integer filterTypeid;
	private Integer filterid;

	public RecipeFilter() {
	}

	public RecipeFilter(Integer recipeid, Integer filterTypeid, Integer filterid) {
		this.recipeid = recipeid;
		this.filterTypeid = filterTypeid;
		this.filterid = filterid;
	}

	public Integer getRecipeFilterid() {
		return this.recipeFilterid;
	}

	public void setRecipeFilterid(Integer recipeFilterid) {
		this.recipeFilterid = recipeFilterid;
	}

	public Integer getRecipeid() {
		return this.recipeid;
	}

	public void setRecipeid(Integer recipeid) {
		this.recipeid = recipeid;
	}

	public Integer getFilterTypeid() {
		return this.filterTypeid;
	}

	public void setFilterTypeid(Integer filterTypeid) {
		this.filterTypeid = filterTypeid;
	}

	public Integer getFilterid() {
		return this.filterid;
	}

	public void setFilterid(Integer filterid) {
		this.filterid = filterid;
	}

}
