package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * RecipeCollect generated by hbm2java
 */
public class RecipeCollect implements java.io.Serializable {

	private Integer cecipeCollectid;
	private Integer recipeid;
	private Boolean isCollected;
	private Date collectedTime;

	public RecipeCollect() {
	}

	public RecipeCollect(Integer recipeid, Boolean isCollected, Date collectedTime) {
		this.recipeid = recipeid;
		this.isCollected = isCollected;
		this.collectedTime = collectedTime;
	}

	public Integer getCecipeCollectid() {
		return this.cecipeCollectid;
	}

	public void setCecipeCollectid(Integer cecipeCollectid) {
		this.cecipeCollectid = cecipeCollectid;
	}

	public Integer getRecipeid() {
		return this.recipeid;
	}

	public void setRecipeid(Integer recipeid) {
		this.recipeid = recipeid;
	}

	public Boolean getIsCollected() {
		return this.isCollected;
	}

	public void setIsCollected(Boolean isCollected) {
		this.isCollected = isCollected;
	}

	public Date getCollectedTime() {
		return this.collectedTime;
	}

	public void setCollectedTime(Date collectedTime) {
		this.collectedTime = collectedTime;
	}

}
