package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

/**
 * RecipeShareTag generated by hbm2java
 */
public class RecipeShareTag implements java.io.Serializable {

	private Integer recipeShareTagid;
	private String recipeShareTagName;
	private Boolean deleteTag;

	public RecipeShareTag() {
	}

	public RecipeShareTag(String recipeShareTagName, Boolean deleteTag) {
		this.recipeShareTagName = recipeShareTagName;
		this.deleteTag = deleteTag;
	}

	public Integer getRecipeShareTagid() {
		return this.recipeShareTagid;
	}

	public void setRecipeShareTagid(Integer recipeShareTagid) {
		this.recipeShareTagid = recipeShareTagid;
	}

	public String getRecipeShareTagName() {
		return this.recipeShareTagName;
	}

	public void setRecipeShareTagName(String recipeShareTagName) {
		this.recipeShareTagName = recipeShareTagName;
	}

	public Boolean getDeleteTag() {
		return this.deleteTag;
	}

	public void setDeleteTag(Boolean deleteTag) {
		this.deleteTag = deleteTag;
	}

}
