package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

/**
 * RecipeIngredient generated by hbm2java
 */
public class RecipeIngredient implements java.io.Serializable {

	private Integer recipeIngredientid;
	private Integer recipeid;
	private Integer ingredientid;
	private Integer type;
	private Integer quantity;

	public RecipeIngredient() {
	}

	public RecipeIngredient(Integer recipeid, Integer ingredientid, Integer type, Integer quantity) {
		this.recipeid = recipeid;
		this.ingredientid = ingredientid;
		this.type = type;
		this.quantity = quantity;
	}

	public Integer getRecipeIngredientid() {
		return this.recipeIngredientid;
	}

	public void setRecipeIngredientid(Integer recipeIngredientid) {
		this.recipeIngredientid = recipeIngredientid;
	}

	public Integer getRecipeid() {
		return this.recipeid;
	}

	public void setRecipeid(Integer recipeid) {
		this.recipeid = recipeid;
	}

	public Integer getIngredientid() {
		return this.ingredientid;
	}

	public void setIngredientid(Integer ingredientid) {
		this.ingredientid = ingredientid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
