package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

/**
 * SharePlatform generated by hbm2java
 */
public class SharePlatform implements java.io.Serializable {

	private Integer sharePlatformid;
	private String name;
	private String describe;

	public SharePlatform() {
	}

	public SharePlatform(String name, String describe) {
		this.name = name;
		this.describe = describe;
	}

	public Integer getSharePlatformid() {
		return this.sharePlatformid;
	}

	public void setSharePlatformid(Integer sharePlatformid) {
		this.sharePlatformid = sharePlatformid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

}
