package com.ym.traegergill.modelBean;
// Generated 2017-10-23 17:20:01 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String account;
	private String password;
	private String firstname;
	private String lastname;
	private String userFigure;
	private Integer tuyaUid;
	private String token;
	private Date signTime;

	public User() {
	}

	public User(String account, String password, String firstname, String lastname, String userFigure, Integer tuyaUid,
			String token, Date signTime) {
		this.account = account;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.userFigure = userFigure;
		this.tuyaUid = tuyaUid;
		this.token = token;
		this.signTime = signTime;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getUserFigure() {
		return this.userFigure;
	}

	public void setUserFigure(String userFigure) {
		this.userFigure = userFigure;
	}

	public Integer getTuyaUid() {
		return this.tuyaUid;
	}

	public void setTuyaUid(Integer tuyaUid) {
		this.tuyaUid = tuyaUid;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getSignTime() {
		return this.signTime;
	}

	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

}
